version: '3.3'

services:
    backend:
        image: mararek/phishing-api:latest
        restart: unless-stopped
        ports:
            - 50010:5000
        env_file:
            - ./api.env
        depends_on: 
            - db
        networks:
            - api_network
    db:
        image: postgres:12-alpine
        env_file:
            - ./api.env
        volumes: 
            - ./database:/var/lib/postgresql/data/pgdata
        expose:
            - 5432
        restart: unless-stopped
        networks:
            - api_network

networks:
    api_network:
