swagger: "2.0"
info:
  description: This is the swagger specs for phishing detection API project
  version: "0.0.1"
  title: Phishing API backend
consumes:
  - application/json
produces:
  - application/json

basePath: /api/v1

# Paths supported by this application
paths:
  /check/domain:
    post:
      operationId: api.main.check_domain
      tags:
      - checks
      summary: Checks domain's evilness 
      description: When given a domain, checks if it is evil and returns proper response
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: formData
          name: domain
          type: string
          description: Full domain.
      responses:
        200:
          description: Domain's details

  /check/ip:
    post:
      operationId: api.main.check_ip
      tags:
      - checks
      summary: Checks ip's evilness 
      description: When given an ip, checks if it is evil and returns proper response
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: formData
          name: ip
          type: string
          description: Full ip.      
      responses:
        200:
          description: IP's details

  /remote/urlscan:
    post:
      operationId: api.remote.scan_urlscan
      tags:
      - remote
      summary: Checks results from urlscan
      description: When given an url, checks in urlscan if it is evil and returns proper response
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: formData
          name: ip
          type: string
          description: Full ip.      
      responses:
        200:
          description: Scan details
        400:
          description: Wrong data

  /remote/safebrowsing:
    post:
      operationId: api.remote.scan_safebrowsing
      tags:
      - remote
      summary: Checks results from Google SafeBrowsing API
      description: When given an url, checks in SafeBrowsing if it is malicious and returns proper response
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: formData
          name: domain_or_ip
          type: string
          description: Full ip or domain.      
      responses:
        200:
          description: Scan details
        400:
          description: Wrong data