class Const:
    WEEK_DAYS = 7
    ENTROPY_PHISHING_MIN = 3.65
    LIFE_LEN_PHISHING_CERT = WEEK_DAYS 
    URLSCAN_WAIT_SECONDS = 15 # sec
    URLSCAN_NOT_FINISHED_ERROR = 'URLSCAN not finished'
    URLSCAN_FINISHED_MESSAGE = 'URLSCAN finished'
    UNKNOWN_RESULTS_MESSAGE = 'Unknown'