class Const:
    DAY = 1
    WEEK_DAYS = 7
    FIVE_WEEK_DAYS = 5
    ENTROPY_PHISHING_MIN = 3.65
    LIFE_LEN_PHISHING_CERT = WEEK_DAYS 
    URLSCAN_WAIT_SECONDS = 5 # sec
    URLSCAN_NOT_FINISHED_ERROR = 'URLSCAN not finished'
    URLSCAN_FINISHED_MESSAGE = 'URLSCAN finished'
    UNKNOWN_RESULTS_MESSAGE = 'Unknown results'
    WRONG_DATA_MESSAGE = 'Wrong data'